### ISSUE TITLE
Implement Cognito authorization

### ISSUE THREAD

**Issue by Turbiani** [flpStrri/Lilium#16]
**Is your feature request related to a problem? Please describe.**
Implementing Cognito on JS backend is not something well documented online, if Lilium could have a good starting boilerplate for this code it could save a big time of its users. Also, with that we can implement some directives exemples to " lock" some mutations and queries based on user roles.

**Describe the solution you'd like**
Implement basic auth methods using the `aws-sdk`, push the user info from the `Authorization` header and implement some directives using it.

**Comment by flpStrri** [comment]
Would you mind working on some auth, other than this? You can start mocking a user object into context, I hope to decide how to push it there soon. 😆

**Comment by flpStrri** [comment]
@Turbiani, can you please review the directive I did on https://github.com/flpStrri/Lilium/pull/19, since you have done that in the past?
